- hosts: mysql
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Configure MySQL
      shell: |
        mysql -e "CREATE USER 'web_user'@'%' IDENTIFIED BY 'password';"
        mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'web_user'@'%';"
        mysql -e "FLUSH PRIVILEGES;"
        mysql -e "CREATE DATABASE testdb;"
        mysql -e "USE testdb; CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));"
        mysql -e "USE testdb; INSERT INTO users (name) VALUES ('Test User');"
      args:
        executable: /bin/bash
